FIRST_NAME_MAX_LENGTH = 50
LAST_NAME_MAX_LENGTH = 50

EMAIL_FIELD = 'email'
FIRST_NAME_FIELD = 'first_name'
LAST_NAME_FIELD = 'last_name'
IS_STAFF_FIELD = 'is_staff'
IS_SUPERUSER_FIELD = 'is_superuser'